### ISSUE TITLE
Shell script error on installing custom image (unbound local variable)

### ISSUE THREAD

**Issue by igor-susic** [GoogleCloudDataproc/custom-images#104]
To continue on previous closed issue:
* https://github.com/GoogleCloudDataproc/custom-images/issues/99

Seems like there are more issues in the script there now the issue is:
````bash

+ [[ -z '' ]]
/tmp/tmp5f60ccrr: line [133](https://gitlab.example.com/example/-/jobs/6431146#L133): num_src_certs: unbound variable
````

cc: @cjac

**Comment by aliaksei-shlemiankou-unity** [comment]
Having the same issue as well. 
Using the latest version of the code produces the same error. 
Likely related to this [PR](https://github.com/GoogleCloudDataproc/custom-images/commit/bdd715209557668e6a3a270a041ae47e80eabd8a#diff-9c5d2fb4f17dc7df741e9c63391616de2a30590e65d2bc5ac8e18f2c76a297a9R102)

**Comment by cjac** [comment]
Okay, I'll look at it tomorrow.  Would you consider installing a cert in the efi trust db?

**Comment by cjac** [comment]
I believe I fixed the unbound variable issue in my WIP fork.  Can you confirm?

**Comment by igor-susic** [comment]
Just tested it, the fix worked as expected. Let's merge it 👍
