### ISSUE TITLE
RuntimeError in Custom Images Python Script

### ISSUE THREAD

**Issue by Leectan** [GoogleCloudDataproc/custom-images#43]
Followed exact steps provided by GCP Dataproc, shell script contains just a simple "apt-get -y update"

Any help and suggestion is appreciated. 

<img width="1281" alt="100" src="https://user-images.githubusercontent.com/24819052/79150055-1c34a500-7d96-11ea-9746-6f27aaabd60c.png">

**Comment by medb** [comment]
Did you check logs as suggested in error message?

**Comment by Leectan** [comment]
<img width="1004" alt="Screen Shot 2020-04-13 at 3 16 28 PM" src="https://user-images.githubusercontent.com/24819052/79152441-32dcfb00-7d9a-11ea-9dd3-7bf485f6a457.png">

**Comment by Leectan** [comment]
I did, went into run.sh and looked at like 37, not seeing anything wrong there.

**Comment by medb** [comment]
You need to update Bash to version 4:
https://github.com/GoogleCloudDataproc/custom-images#requirements

**Comment by Leectan** [comment]
Did. Same error

**Comment by Leectan** [comment]
Why are you closing this if it is not resolved?

**Comment by medb** [comment]
I closed this issue because this is the same as we already saw in the past: https://github.com/GoogleCloudDataproc/custom-images/issues/35

Are you sure that you have upgraded Bash? May you post output of the command:
```
sh --version
bash --version
/bin/bash --version
/usr/bin/bash --version
```
