### ISSUE TITLE
Allow using latest version of image

### ISSUE THREAD

**Issue by swt2c** [GoogleCloudDataproc/custom-images#53]
The generate_custom_image.py script seems to require specifying an exact version with `--dataproc-version`.  It would be nice if you could specify, for example, `1.5-debian10` to get the latest version of the 1.5-debian10 image, rather than having to specify 1.5.29-debian10.

**Comment by pavantrue** [comment]
+1
It is pain to pass explicit image version to the script and build images. Moreover google deprecate all custom images after 30days from time it got built. Also, there i no way to know what image id is being released for respective versions except looking at the release notes link. It would be great if we can have some API to give this information

**Comment by medb** [comment]
This is trivial to automate w/ something like this:

```bash
gcloud compute images list --project cloud-dataproc \
  --filter='labels.goog-dataproc-version:2-0-*-debian10 AND creationTimestamp>-P4W' \
  --format='table(creationTimestamp,name,labels.goog-dataproc-version)'
```
