### ISSUE TITLE
Error: Requested disk size cannot be smaller than the image size

### ISSUE THREAD

**Issue by TiansuYu** [GoogleCloudDataproc/custom-images#68]
Encountered the following error: `Invalid value for field 'resource.sizeGb': '20'. Requested disk size cannot be smaller than the image size (30 GB)` 

This is produced using the following command `python xxxxx/custom-images/generate_custom_image.py --image-name xxxx-dataproc-custom-image-v0 --dataproc-version 2.0-debian10 --customization-script custom_image_xxx.sh --zone europe-west4-b --gcs-bucket dataproc-temp-europe-west4-xxxx`. (Some sensitive info are marked up.) 

Wonder why the image is so large. (The .sh file only installs like 10 python dependencies, and certainly no large ones.)

**Comment by medb** [comment]
This is limitation that stems from the size of the base Dataproc 2.0 image, it's required to accommodate all software supported by Dataproc.

**Comment by TiansuYu** [comment]
Maybe this is a stupid question, but I didnt manually change any setting about image_size here, does that mean this is somehow restricted by e.g. my docker settings or something else, and how do I manually change this?

**Comment by medb** [comment]
No, it is because different Dataproc base image versions (1.4, 1.5, 2.0, etc) have different requirements for minimum VM boot disk size.
