### ISSUE TITLE
Cannot find dataproc base image released over 9 days ago

### ISSUE THREAD

**Issue by stalone-dev** [GoogleCloudDataproc/custom-images#71]
We can see in [the release notes page](https://cloud.google.com/dataproc/docs/release-notes#January_17_2022) that `2.0.29-debian10` was released 9 days ago (Jan 17th). However, the latest version of `generate_custom_image.py` fails as follow:

Command:

```
python generate_custom_image.py \
    --image-name custom-image-2-0-29-debian10 \
    --dataproc-version 2.0.29-debian10 \
    --customization-script ~/custom-script.sh \
    --zone us-central1-f \
    --gcs-bucket gs://my-test-bucket
```

Traceback:
```
Traceback (most recent call last):
  File "generate_custom_image.py", line 95, in <module>
    main()
  File "generate_custom_image.py", line 86, in main
    args = parse_args(sys.argv[1:])
  File "generate_custom_image.py", line 57, in parse_args
    args_inferer.infer_args(args)
  File "/dataproc-custom-images/custom_image_utils/args_inferer.py", line 225, in infer_args
    _infer_base_image(args)
  File "/dataproc-custom-images/custom_image_utils/args_inferer.py", line 191, in _infer_base_image
    args.dataproc_version)
  File "/dataproc-custom-images/custom_image_utils/args_inferer.py", line 175, in _get_dataproc_image_path_by_version
    "Cannot find dataproc base image with dataproc-version=%s." % version)
RuntimeError: Cannot find dataproc base image with dataproc-version=2.0.29-debian10.
```

As a workaround a Google Cloud Employee [suggested](https://stackoverflow.com/a/69519169) dropping the minor version (e.g `2.0-debian10`) but that would make environments and workloads non-deterministic unfortunately.

Could this issue be investigate a bit further as seems to be related to GCP's release & tagging process?

**Comment by crogers923** [comment]
I tried dropping the minor version, and it found 2.0.28, which according to the docs is still impacted by the log4j issue.

**Comment by medb** [comment]
The latest images released last week already labeled - generally new images are labeled 7 days after release.

**Comment by stalone-dev** [comment]
Funnily enough I can confirm `2.0.29-debian10` can now be reached (10 days later after release).
